
module.exports = {
	MDLW_ERR_ID_VALIDATION: 'Invalid ID parameter. The ID must be a positive integer.',
	MDLW_ERR_TEXT_VALIDATION: 'Invalid search text. The text cannot be empty or null.',
	MDLW_ERR_COUNTRY_ID_NOT_FOUND: 'Country not found. Please verify the provided country ID.',
	MDLW_ERR_COUNTRIES_NOT_FOUND: 'Countries not found.',
	MDLW_ERR_COUNTRY_NAME_NOT_FOUND: 'Country not found.',
	MDLW_ERR_STATE_ID_NOT_FOUND: 'State not found. Please verify the provided state ID.',
	MDLW_ERR_STATES_NOT_FOUND: 'States not found.',
	MDLW_ERR_USER_ID_NOT_FOUND: 'User not found. Please verify the provided user ID.',
	MDLW_ERR_USER_ALREADY_EXISTS: 'User already exists. The username or email is already registered.',
	MDLW_ERR_USER_REGISTRATION_FAILED: 'User registration failed. Please try again.',
	MDLW_ERR_USER_MISSING_FIELDS: 'Missing required fields. Please provide all required user information.',
	MDLW_ERR_LOGIN_MISSING_FIELDS: 'Missing required fields. Please provide login credentials.',
	MDLW_ERR_INVALID_CREDENTIALS: 'Invalid credentials. Please check your username/email and password.',
	MDLW_ERR_USER_NOT_ACTIVE: 'User account is not active. Please contact support.',
	MDLW_ERR_LOGIN_FAILED: 'Login failed. Please try again.',
	MDLW_ERR_NO_UPDATE_DATA: 'No data provided to update. Please provide at least one field to update.',
	MDLW_ERR_USER_UPDATE_FAILED: 'User update failed. Please try again.',
	MDLW_ERR_USERNAME_EMAIL_IN_USE: 'Username or email is already in use by another user.',
	MDLW_ERR_PASSWORD_MISSING_FIELDS: 'Missing required fields. Please provide current and new password.',
	MDLW_ERR_INVALID_CURRENT_PASSWORD: 'Current password is incorrect.',
	MDLW_ERR_PASSWORD_UPDATE_FAILED: 'Password update failed. Please try again.',
	MDLW_ERR_USER_DELETE_FAILED: 'User deletion failed. Please try again.',
};
